version: '3.9'
services:
  back:
    build: BimIot-Back
    image: bimiotback:latest
    container_name: bimiot-backend
    ports:
      - 8082:8082
    networks:
      - frontback

  front:
    build: BimIot-Front
    image: bimiotfront:latest
    ports:
      - 8080:8080
    depends_on:
      - back
    networks:
      - frontback

networks:
  frontback:
    driver: bridge